# Generated by Django 5.2.6 on 2025-09-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(max_length=20)),
                ('acceptance_rate', models.FloatField(default=0.0)),
                ('discuss_count', models.BigIntegerField(default=0)),
                ('submissions_count', models.BigIntegerField(default=0)),
                ('related_topics', models.TextField(blank=True, null=True)),
                ('likes', models.BigIntegerField(default=0)),
                ('dislikes', models.BigIntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('similar_questions', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
