# Generated by Django 5.2.6 on 2025-10-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problems_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='status',
            field=models.CharField(default='unattempted', max_length=20),
        ),
    ]
