# Generated by Django 5.2.6 on 2025-10-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problems_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='acceptance_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
