# Generated by Django 5.2.6 on 2025-11-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problems_acceptance_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='problems.problems')),
            ],
        ),
    ]
