# Generated by Django 5.2.6 on 2025-10-22 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comments_parent'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='is_solution',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='problem',
        ),
        migrations.AddField(
            model_name='comments',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='comments',
            name='object_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['content_type', 'object_id'], name='comments_co_content_0da227_idx'),
        ),
    ]
