# Generated by Django 5.2.6 on 2025-10-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='sub_indicater',
            field=models.CharField(choices=[('pink', 'pink'), ('green', 'green'), ('blue', 'blue'), ('red', 'red'), ('yellow', 'yellow'), ('white', 'white')], default='blue', max_length=6),
        ),
    ]
