# Generated by Django 5.2.6 on 2025-10-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submissions_note_submissions_sub_indicater'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='last_executed_input',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
