# Generated by Django 5.2.6 on 2025-10-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_submissions_last_executed_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='error_message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
