# Generated by Django 5.2.6 on 2025-10-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submissions_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='passed_test_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submissions',
            name='total_test_cases',
            field=models.IntegerField(default=0),
        ),
    ]
