# Generated by Django 5.2.6 on 2025-10-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_submissions_passed_test_cases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='expected_output',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='user_output',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
