# Generated by Django 5.2.6 on 2025-10-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_submissions_expected_output_submissions_user_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='expected_output',
        ),
    ]
