# Generated by Django 5.2.6 on 2025-10-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_remove_submissions_expected_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='histogram_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
