# Generated by Django 5.2.6 on 2025-10-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0008_submissions_histogram_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatetestcases',
            name='code_solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
