# Generated by Django 5.2.6 on 2025-10-22 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_solutuionlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
