# Generated by Django 5.2.6 on 2025-10-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_solutions_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
