# Generated by Django 5.2.6 on 2025-10-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeplperFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_list_helper_function', models.TextField(blank=True, null=True)),
                ('trees_helper_functions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
